### ISSUE TITLE
Ed25519 to X25519 Conversion algorithm

### ISSUE THREAD

**Issue by jose-gataca** [digitalbazaar/x25519-key-agreement-key-2020#11]
Hi,

I am building a typescript application and wanted it to be compatible with your [did method key library](https://github.com/digitalbazaar/did-method-key)

However, I am struggling to use the generated X25519 KeyAgreement keys, and I can't get to understand how you are deriving them.

As far as I understand, the transportation from Ed25519 to X25519 is possible, but one would need to translate the point coordinates, as explained  [in this thread](https://crypto.stackexchange.com/questions/98561/ed25519-to-x25519-transportation)

Other implementations, like the one from Noble:[noble-ed25519#x25519-and-curve25519](https://github.com/paulmillr/noble-ed25519#x25519-and-curve25519) which you already checked on Issue #7 [](https://github.com/digitalbazaar/x25519-key-agreement-key-2020/issues/7) do in fact use that approach:
See line 573 https://github.com/paulmillr/noble-ed25519/blob/main/index.ts

The thing is that your approach in:
https://github.com/digitalbazaar/x25519-key-agreement-key-2020/blob/main/lib/crypto-nacl.js
seems to generate X25519 private keys that can be used for a DH exchange. 
Regarding your implementation, I have tried to test it and can't replicate it within my application because I can't identify which hash algorithm does _nacl.lowlevel.crypto_hash_ use. Reading the documentation, I understood it should be a SHA-512; but testing it against the own nacl hash function (which is in fact SHA-512) it doesn't produce the same result.

`
const utf8Encode = new TextEncoder();
const encoded = utf8Encode.encode("Test message");
const hash2 = new Uint8Array(64);
nacl.lowlevel.crypto_hash(hash2, encoded, 32);
let hashed = nacl.hash(encoded);
console.log("HASH TEST", hashed, toHexString(hashed), hash2, toHexString(hash2))`

Could you help me with that?

**Comment by dlongley** [comment]
In your test, you need to pass `encoded.length` instead of `32` (to use the proper length of the encoded `"Test message"` string you chose). Once you do this, you'll get the same hash value.

Note that you can see that `nacl.hash` just reuses the "lowlevel" `crypto_hash` hash function here:

https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L1129-L1134
https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L897 (exported as "nacl.lowlevel")

**Comment by jose-gataca** [comment]
Thanks for the answer. That was indeed the issue. I was confused because the hash effectively is computed only for the first half of the private key (which maps to the d coordinate).

Regarding the algorithm for key derivation, is it possible either that the noble library or yours uses the algorithm to derive the public key instead of the private key? Would you know which is wrong?

**Comment by dlongley** [comment]
Closing as it appears this is resolved. Regarding derivation of keys, the X25519 public key is translated from the Ed25519 public key. The private key in these cases is the random seed for Ed25519 and the clamped SHA-512 hash of the secret key for X25519. The public key would be a scalar point multiplication of the base point by the private key.

One thing that does need to get sorted amongst private key representations is whether the public key should be concatenated onto the end of the private key as it commonly is with Ed25519 (including in implementations like libsodium) but where it is not for X25519 (including in implementations like libsodium). Having these two be different sizes also helps prevent confusion between the two.

For further rationale, see: https://crypto.stackexchange.com/questions/54353/why-are-nacl-secret-keys-64-bytes-for-signing-but-32-bytes-for-box
